name: Building ubuntu Touch

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    

    steps:
       - name: Checkout
         uses: actions/checkout@master
         

       - name: remove pkg and setting repo
         run: |
            sudo apt update && sudo apt install git
            git clone https://github.com/SA-17/rm_pkg pkg && cd pkg && bash setup.sh
            cd .. && sudo -E apt-get -qq update
            sudo rm -rf /opt/*
            sudo rm -rf /usr/share/dotnet
            sudo rm -rf "/usr/local/share/boost"
            sudo rm -rf "$AGENT_TOOLSDIRECTORY"

       - name: Adding required software
         run: |
              sudo dpkg --add-architecture i386
              sudo apt update
              curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
              chmod a+rx ~/bin/repo

       - name: Building kernel
         run: |
               ln -s deviceinfo-** deviceinfo
               sudo bash build.sh -b workdir 
               
