name: Building ubuntu Touch

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:
       - name: Checkout
         uses: actions/checkout@master
         

       - name: remove pkg and setting repo
         run: |
            sudo apt update && sudo apt install git
            git clone https://github.com/SA-17/rm_pkg pkg && cd pkg && bash setup.sh
            cd .. && sudo -E apt-get -qq update
            sudo rm -rf /opt/*
            sudo rm -rf /usr/share/dotnet
            sudo rm -rf "/usr/local/share/boost"
            sudo rm -rf "$AGENT_TOOLSDIRECTORY"

       - name: Adding required software
         run: |
              sudo dpkg --add-architecture i386
              sudo apt update
              sudo apt install git gnupg flex bison gperf build-essential \
              zip bzr curl libc6-dev libncurses5-dev:i386 x11proto-core-dev \
              libx11-dev:i386 libreadline6-dev:i386 libgl1-mesa-glx:i386 \
              libgl1-mesa-dev g++-multilib mingw-w64-i686-dev tofrodos \
              python3-markdown libxml2-utils xsltproc zlib1g-dev:i386 schedtool \ -y
              mkdir -p ~/bin
              echo export PATH=\$PATH:\$HOME/bin >> ~/.bashrc
              source ~/.bashrc
              curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
              chmod a+rx ~/bin/repo

       - name: Building kernel
         run: |
               ln -s deviceinfo-** deviceinfo
               sudo bash build.sh -b workdir 
               
